# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.14
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # ESLint 
      - run:
          name: "Eslint"
          command: yarn eslint -- --format junit -o reports/junit/js-lint-results.xml

      - run:
          name: "Flow"
          command: yarn flow

      - run:
          name: "Prettier"
          command: yarn prettier:circleci        

      # Jest
      - run:
          name: "Jest"
          command: yarn jest -- --ci --coverage --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

      # Coveralls 
      - run:
          name: "Coveralls"
          command: yarn jest --coverage --coverageReporters=text-lcov | yarn coveralls
